branch: main
check:
- TAG_SECURITY_LEVEL_1
directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
output: cli
external-checks-dir: tag_checks
